### ISSUE TITLE
type "+/-" "π" gives wrong results.

### ISSUE THREAD

**Issue by chaowangCanada** [transcendental-team/transcend-calculations#20]
type "+/-" "π" gives wrong results.

Current behavior:  type "+/-" "π", "invalid expression"

Correct behavior: type "+/-" "π", " -3.14..." 

Same issue for "e"

**Comment by tshaynik** [comment]
Thanks for catching this. This is now fixed.

**Comment by chaowangCanada** [comment]
@dkundathagard  

type "+/-" "π" still get, "invalid expression".  "(-e" works fine.

I change it for release 1.2. You can have a look or change on your way,
